# utils/symbols.py
NSE_SYMBOLS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "BHARTIARTL.NS", 
    "SBIN.NS", "INFY.NS", "LICI.NS", "ITC.NS", "HINDUNILVR.NS", "LT.NS", 
    "BAJFINANCE.NS", "ADANIENT.NS", "MARUTI.NS", "SUNPHARMA.NS", "TITAN.NS", 
    "ADANIPORTS.NS", "ULTRACEMCO.NS", "ASIANPAINT.NS", "ONGC.NS", "COALINDIA.NS", 
    "ZOMATO.NS", "PAYTM.NS", "TATASTEEL.NS", "NTPC.NS", "M&M.NS", "JSWSTEEL.NS"
]
